### PR TITLE
Convert README to markdown

### PR DESCRIPTION
**Pull request by MatheusRich**
I think using markdown improves the readability of the document, and makes easier to understand and contribute for parslet!

### CODE REVIEW

**Comment by kschiess** [comment]
I don't agree with any of this. Parslet is not the place for syntax wars.

**Comment by MatheusRich** [comment]
@kschiess Maybe I didn't express myself well. I'm not complaining about syntax, my PR was to make Readme actually display nicely on github, not just plain text as it is now:

image

**Comment by kschiess** [comment]
I personally am old enough to like the plain text better in this case.

**Comment by jethrodaniel** [comment]
lol, @kschiess  how many of these PR's have you struck down over the course of this repo?

Might want to add that such a PR won't be accepted to the README or to a PR template to avoid this in the future.

**Comment by kschiess** [comment]
You're right. 

I am under the constant illusion that this is an obvious detail and has no importance. But apparently Markdown has become important while I wasn't lookin' ;)

**Comment by MatheusRich** [comment]
I just think that there's no reason to keep it in plain text when Github fully supports a pretty preview of Markdown and it makes a subject like parsers/compiler less "scarier" to a new user. Anyway, I got your point.

**Pull request closed without merging**
