### PR TITLE
fix #151 - Rspec has issues with 'cause' on 'Parslet::ParseFailed'.  …

### LINKED ISSUE #151: Rspec has issues with 'cause' on 'Parslet::ParseFailed'
rspec seems to now traverse exception chains and attempts to properly format them for output.  When it encounters a `Parslet::ParseFailed` exception it has problems because of the `cause` method.

In this case, rspec recursively calls `cause` on exceptions which works the first time to get the `Parslet::Cause` object, but fails after that because `Parslet::Cause` does not have a `cause` method.

Fixing this is going to either require defining a `cause` method on `Parslet::Cause` that returns `nil`, or renaming the `cause` method on `Parslet::ParseFailed` to something else.

In addition, because Ruby automatically populates the `cause` of an exception with the original exception when re-raising exceptions, it is not possible to simply bypass this problem by raising a new exception without setting the cause.

I would be inclined to suggest renaming the method since it is actually in conflict with a method on Exception that has been there since ruby 2.1.

I would be happy to create a pull request for this, but wanted to hear your thoughts on the approach since this would represent a fairly significant and possibly breaking change.

### PR DESCRIPTION
**Pull request by johnnaegle**
Rename cause to parse_failure_cause

### CODE REVIEW

**Comment by kschiess** [comment]
I'll merge your PR if you remove all whitespace cleanup from it...

**Comment by johnnaegle** [comment]
How about I run a code cleaner and remove trailing whitespace on the whole project?

**Comment by kschiess** [comment]
I don't think that's a good idea. Here's what I would like from you: Make the smallest possible changeset that implements the goal of this PR - then I'll happily merge your contribution.

If you want to clean whitespace, do it where changes are needed anyway.

**Comment by kschiess** [comment]
I've just merged a PR that fixes this bug.

**Pull request closed without merging**
