### PR TITLE
fix #151 

### LINKED ISSUE #151: Rspec has issues with 'cause' on 'Parslet::ParseFailed'
rspec seems to now traverse exception chains and attempts to properly format them for output.  When it encounters a `Parslet::ParseFailed` exception it has problems because of the `cause` method.

In this case, rspec recursively calls `cause` on exceptions which works the first time to get the `Parslet::Cause` object, but fails after that because `Parslet::Cause` does not have a `cause` method.

Fixing this is going to either require defining a `cause` method on `Parslet::Cause` that returns `nil`, or renaming the `cause` method on `Parslet::ParseFailed` to something else.

In addition, because Ruby automatically populates the `cause` of an exception with the original exception when re-raising exceptions, it is not possible to simply bypass this problem by raising a new exception without setting the cause.

I would be inclined to suggest renaming the method since it is actually in conflict with a method on Exception that has been there since ruby 2.1.

I would be happy to create a pull request for this, but wanted to hear your thoughts on the approach since this would represent a fairly significant and possibly breaking change.

### PR DESCRIPTION
**Pull request by aoitaku**
I think the name of `Parslet::Cause` has no problem, so I keep it.

### CODE REVIEW

**Comment by olbrich** [comment]
looks good, but I'm having trouble accessing the travis build to see if it's actually working properly.

**Comment by aoitaku** [comment]
Travis results are :

- Ruby: 1.9.3 - failed
- Ruby: 2.0 - succeeded
- Ruby: 2.1 - failed

Ruby 1.9.3 is no longer supported. This can be ignored.

Ruby 2.1 failed because:

```
NoMethodError: undefined method `spec' for nil:NilClass
An error occurred while installing parslet (1.7.1), and Bundler cannot continue.
```

Ruby 2.1 or higher, bundler needs to be upgraded because rubygems is updated, but travis uses older version. ([see detail](https://github.com/travis-ci/travis-ci/issues/5239))

**Comment by aprescott** [comment]
I believe a rebase of this PR to include #170 should get the build passing.

**Comment by aoitaku** [comment]
build got passed thanks to @aprescott.

**Comment by kschiess** [comment]
Thanks a lot for your work!

**Pull request merged**
