### PR TITLE
Convert README to markdown for better rendering

### PR DESCRIPTION
**Pull request by schneems**

### CODE REVIEW

**Comment by kschiess** [comment]
I'd rather not. I like the way the current markdown also renders in `cat`. Thank you for suggesting this and for taking the time to propose a PR!

cheers

**Comment by schneems** [comment]
Are you talking about the command line tool? How does using markdown decrease readability there? Markdown is designed to be readable in both raw text and rendered HTML formats.

Can you say more?

**Comment by kschiess** [comment]
Markdown is still inferior to actual plain text for this application. Also, there is really no discussion here; this is open source: if you want to change it without me, fork it.

**Comment by schneems** [comment]
> Markdown is still inferior to actual plain text 

I’ve heard you, i’m curious why you say that. What about markdown do you not like? Is it all markdown or just my modifications here? 

> there is really no discussion here

I want to understand you as a maintainer. Ive never heard anyone say what you’ve said and I want to hear more.

**Pull request closed without merging**
